int validaEmail(char *);
int validaCpf(char *);
int validaCep(char *);
int validaPhone(char *);
int validaRg(char *);
int validaNome(char *);
void maskCpf(char *);
void maskCep(char *);
void maskPhone(char *);
void maskRg(char *);
int ehDigito(char);
int ehLetra(char);
int ehBissexto(int);
int ehData(int);
int validarData(char *);